name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          check-latest: true
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: jdk8
          arguments: build --no-build-cache
          gradle-version: wrapper
      - name: Set artifacts output
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Rename build artifacts
        run: mv build/libs/liquidbounceplus-final.jar build/libs/liquidbounceplus.jar
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: liquidbounceplus-${{ steps.vars.outputs.sha_short }}
          path: build/libs/liquidbounceplus-${{ steps.vars.outputs.sha_short }}.jar
